frontend:
  image: tianwens/frontend
  autoscaling:
    averageUtilization: 90
backend:
  image: tianwens/backend
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
