name: build

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: tianwens

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        #run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        run: echo "sha_short=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}  # 测试打印看一下是否正常

      # 本次后端总是报程序的错误（https://127.0.0.1:8080/上可以看到日志：RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.）导致pod起不来，先不查原因，先略过，先不弄后端的，注释掉后端的，不影响整体测试GitOps工作流
      # - name: Build backend and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: backend
      #     push: true
      #     # tags: ${{ env.DOCKERHUB_USERNAME }}/backend:${{ steps.vars.outputs.sha_short }}
      #     tags: ${{ env.DOCKERHUB_USERNAME }}/backend

      - name: Build frontend and push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true  # 下面这里是编译并推送到docker hub的tag
          # tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend

      # 新版本要删掉如下（构建时github action里会看到报错）
      # - name: Update helm values.yaml
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: 'helm/values.yaml'
      #     commitChange: true
      #     branch: main
      #     updateFile: true
      #     message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
      #     changes: |
      #       {
      #         "backend.tag": "${{ steps.vars.outputs.sha_short }}",
      #         "frontend.tag": "${{ steps.vars.outputs.sha_short }}"
      #       }